version: '2'
services:
    investhry-app:
        image: investhry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=investhry-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    investhry-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: investhry-cassandra
    investhry-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=investhry-cassandra
    investhry-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: investhry-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
